Story#99 Promisify createReadStream and createWriteStream
PlayNetwork/fs-promise-util pull request #3
Opened 2017-05-10 00:48 UTC by deepakdahal

- make all the functions consistent to return a Promise
- add tests for the promisified createReadStream and createWriteStream

2017-05-11 14:44 UTC, brozeph requested changes

2017-05-11 14:44 UTC, brozeph commented on README.md
In the code block just above this, can you re-format as follows? (i.e. use the back tick notation "`" and qualify as Javascript) 

```javascript
{
   flags: 'r',
   encoding: null,
   fd: null,
   mode: 0x666,
   autoClose: true
 }
```

2017-05-11 14:44 UTC, brozeph commented on README.md
Same comment for the `options` object documentation above this - I can't put the comment directly on the line of code, but just prior to the `writeContent` example, there is a code block for the options. Can you put that in a block using backticks for consistency?

2017-05-11 20:07 UTC, deepakdahal commented on README.md
this has been taken care of

2017-05-12 01:16 UTC, deepakdahal commented on README.md
taken care of

2017-05-12 16:01 UTC, merged